### ISSUE TITLE
Dark Mode Please?

### ISSUE THREAD

**Issue by ForceGT** [saurabhdaware/text-to-handwriting#50]
**Is your feature request related to a problem? Please describe.**
My eyes are burning xD

**Describe the solution you'd like**
A well developed dark mode with #000 and not #999

**Comment by saurabhdaware** [comment]
Haha is it really needed though? The tool will be used for a limited time right? it makes sense to have a dark mode for something like Twitter or Instagram which you use constantly and can spend hours scrolling through the feed. 

Would like to know thoughts on this

**Comment by ForceGT** [comment]
You know dark mode is really soothing to the eyes 
And going by what you said it's needed for apps like Twitter or Instagram where user retention is high, for this tool you made, a user will spend roughly between 10 min to 30 min typing 
(You know if you see engineering assignments are atleast 10 pages long) so I think that should be a good enough reason to think upon adding dark mode

**Comment by ForceGT** [comment]
Besides I know you're really pro and I shouldn't be telling you how to do what
All I can think of darkmode is[DarkMode.js](https://darkmodejs.learn.uno/) with a small input element anywhere of type checkbox and some css

**Comment by saurabhdaware** [comment]
Yes makes sense, I'll keep this open if anyone wants to work on this.

> Besides I know you're really pro and I shouldn't be telling you how to do what
All I can think of darkmode isDarkMode.js with a small input element anywhere of type checkbox and some css

You can definitely suggest ways to do it, this is the whole point of open-source :D 

Maybe we can have CSS variables and define colors
This is what I do in one of my projects,
```css
body {
  --background-primary: #fff;
  --font-color-primary: #333;
  --elevation-background: #fff;
  --code-background: #f3f3f3;
  --link-color: #006EB8;
  --font-family-primary: 'Noto Sans KR', sans-serif;
}
body.dark {
  --background-primary: #121212;
  --font-color-primary: #ccc; 
  --elevation-background: #1D1D1D;
  --code-background: #222;
  --link-color: #09f;
}

```

an on toggle, I change the class of body
